/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DPexPairInitHashInterface extends ethers.utils.Interface {
  functions: {
    "get()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "get", values?: undefined): string;

  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;

  events: {};
}

export class DPexPairInitHash extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DPexPairInitHashInterface;

  functions: {
    get(overrides?: CallOverrides): Promise<[string]>;

    "get()"(overrides?: CallOverrides): Promise<[string]>;
  };

  get(overrides?: CallOverrides): Promise<string>;

  "get()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    get(overrides?: CallOverrides): Promise<string>;

    "get()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    get(overrides?: CallOverrides): Promise<BigNumber>;

    "get()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    get(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "get()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
